language: java
dist: trusty
jdk:
  - oraclejdk8
  
notifications:
  email:
    - alexander.fedorov@arsysop.ru
    - sergei.kovalchuk@arsysop.ru
    
cache:
  directories:
  - $HOME/.m2

before_install: echo "MAVEN_OPTS='-Xmx2048m'" > ~/.mavenrc

install: true

script: mvn clean verify
