<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="licenses" nsURI="http://www.eclipse.org/passage/lic/licenses/2.0.0"
    nsPrefix="org.eclipse.passage.lic">
  <eClassifiers xsi:type="ecore:EClass" name="AgreementDataDescriptor" instanceClassName="org.eclipse.passage.lic.licenses.AgreementDataDescriptor"
      abstract="true" interface="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="@since 2.1"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CompanyRefDescriptor" instanceClassName="org.eclipse.passage.lic.licenses.CompanyRefDescriptor"
      abstract="true" interface="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="@since 2.0"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EvaluationInstructionsDescriptor" instanceClassName="org.eclipse.passage.lic.licenses.EvaluationInstructionsDescriptor"
      abstract="true" interface="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="@since 2.0"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FeatureGrantDescriptor" instanceClassName="org.eclipse.passage.lic.licenses.FeatureGrantDescriptor"
      abstract="true" interface="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="@since 2.0"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FeatureRefDescriptor" instanceClassName="org.eclipse.passage.lic.licenses.FeatureRefDescriptor"
      abstract="true" interface="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="@since 2.0"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FloatingLicensePackDescriptor" instanceClassName="org.eclipse.passage.lic.licenses.FloatingLicensePackDescriptor"
      abstract="true" interface="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="@since 2.0"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FloatingLicenseRequisitesDescriptor"
      instanceClassName="org.eclipse.passage.lic.licenses.FloatingLicenseRequisitesDescriptor"
      abstract="true" interface="true" eSuperTypes="#//LicenseRequisitesDescriptor">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="@since 2.0"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FloatingServerDescriptor" instanceClassName="org.eclipse.passage.lic.licenses.FloatingServerDescriptor"
      abstract="true" interface="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="@since 2.0"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LicensePlanDescriptor" instanceClassName="org.eclipse.passage.lic.licenses.LicensePlanDescriptor"
      abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="LicensePlanFeatureDescriptor" instanceClassName="org.eclipse.passage.lic.licenses.LicensePlanFeatureDescriptor"
      abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="LicenseRequisitesDescriptor" instanceClassName="org.eclipse.passage.lic.licenses.LicenseRequisitesDescriptor"
      abstract="true" interface="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="@since 2.0"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PersonalFeatureGrantDescriptor" instanceClassName="org.eclipse.passage.lic.licenses.PersonalFeatureGrantDescriptor"
      abstract="true" interface="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="@since 2.0"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PersonalLicensePackDescriptor" instanceClassName="org.eclipse.passage.lic.licenses.PersonalLicensePackDescriptor"
      abstract="true" interface="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="@since 2.0"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PersonalLicenseRequisitesDescriptor"
      instanceClassName="org.eclipse.passage.lic.licenses.PersonalLicenseRequisitesDescriptor"
      abstract="true" interface="true" eSuperTypes="#//LicenseRequisitesDescriptor">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="@since 2.0"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProductRefDescriptor" instanceClassName="org.eclipse.passage.lic.licenses.ProductRefDescriptor"
      abstract="true" interface="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="@since 2.0"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SignatureAttributeDescriptor" instanceClassName="org.eclipse.passage.lic.licenses.SignatureAttributeDescriptor"
      abstract="true" interface="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="@since 2.0"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SignatureDescriptor" instanceClassName="org.eclipse.passage.lic.licenses.SignatureDescriptor"
      abstract="true" interface="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="@since 2.0"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UserGrantDescriptor" instanceClassName="org.eclipse.passage.lic.licenses.UserGrantDescriptor"
      abstract="true" interface="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="@since 2.0"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UserRefDescriptor" instanceClassName="org.eclipse.passage.lic.licenses.UserRefDescriptor"
      abstract="true" interface="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="@since 2.0"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ValidityPeriodClosedDescriptor" instanceClassName="org.eclipse.passage.lic.licenses.ValidityPeriodClosedDescriptor"
      abstract="true" interface="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="@since 2.0"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ValidityPeriodDescriptor" instanceClassName="org.eclipse.passage.lic.licenses.ValidityPeriodDescriptor"
      abstract="true" interface="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="@since 2.0"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VersionMatchDescriptor" instanceClassName="org.eclipse.passage.lic.licenses.VersionMatchDescriptor"
      abstract="true" interface="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="@since 2.0"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AgreementData" eSuperTypes="#//AgreementDataDescriptor">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="@since 2.1"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="identifier" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="file" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hashAlgo" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hash" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EByteArray"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="content" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EByteArray"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="contentType" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CompanyRef" eSuperTypes="#//CompanyRefDescriptor">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="@since 2.0"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="identifier" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="info" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EvaluationInstructions" eSuperTypes="#//EvaluationInstructionsDescriptor">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="@since 2.0"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="expression" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FeatureGrant" eSuperTypes="#//FeatureGrantDescriptor">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="@since 2.0"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="identifier" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="feature" lowerBound="1"
        eType="#//FeatureRef" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="valid" lowerBound="1" eType="#//ValidityPeriod"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vivid" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="capacity" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pack" lowerBound="1" eType="#//FloatingLicensePack"
        eOpposite="#//FloatingLicensePack/features"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FeatureRef" eSuperTypes="#//FeatureRefDescriptor">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="@since 2.0"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="identifier" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="versionMatch" lowerBound="1"
        eType="#//VersionMatch" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FloatingLicenseAccess">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="@since 2.0"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="user" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="server" lowerBound="1"
        eType="#//FloatingServerConnection" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="originLicensePack" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FloatingLicensePack" eSuperTypes="#//FloatingLicensePackDescriptor">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="@since 2.0"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="license" lowerBound="1"
        eType="#//FloatingLicenseRequisites" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="host" lowerBound="1" eType="#//FloatingServer"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="users" lowerBound="1" upperBound="-1"
        eType="#//UserGrant" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="features" lowerBound="1"
        upperBound="-1" eType="#//FeatureGrant" containment="true" eOpposite="#//FeatureGrant/pack"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FloatingLicenseRequisites" eSuperTypes="#//LicenseRequisites #//FloatingLicenseRequisitesDescriptor">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="@since 2.0"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="company" lowerBound="1"
        eType="#//CompanyRef" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="group" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FloatingServer" eSuperTypes="#//FloatingServerDescriptor">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="@since 2.0"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="identifier" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="authentication" ordered="false"
        unique="false" lowerBound="1" eType="#//EvaluationInstructions" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FloatingServerConnection">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="@since 2.0"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ip" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="port" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="authentication" ordered="false"
        unique="false" lowerBound="1" eType="#//EvaluationInstructions" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GrantAcqisition">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="@since 2.0"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="identifier" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="feature" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="grant" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="user" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="created" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LicensePlan" eSuperTypes="#//LicensePlanDescriptor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="identifier" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="agreements" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="@since 2.1"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="features" lowerBound="1"
        upperBound="-1" eType="#//LicensePlanFeature" containment="true" eOpposite="#//LicensePlanFeature/plan">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="@since 2.0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="personal" upperBound="-1"
        eType="#//PersonalLicensePack" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="@since 2.0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="floating" upperBound="-1"
        eType="#//FloatingLicensePack" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="@since 2.0"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LicensePlanFeature" eSuperTypes="#//LicensePlanFeatureDescriptor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="feature" lowerBound="1"
        eType="#//FeatureRef" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="@since 2.0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="plan" lowerBound="1" eType="#//LicensePlan"
        eOpposite="#//LicensePlan/features">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="@since 2.0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vivid" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="@since 2.0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="capacity" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="@since 2.0"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LicenseRequisites" abstract="true" eSuperTypes="#//LicenseRequisitesDescriptor">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="@since 2.1"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="identifier" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="issueDate" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="plan" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="product" lowerBound="1"
        eType="#//ProductRef" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="valid" lowerBound="1" eType="#//ValidityPeriod"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="signature" eType="#//Signature"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="agreements" upperBound="-1"
        eType="#//AgreementData" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PersonalFeatureGrant" eSuperTypes="#//PersonalFeatureGrantDescriptor">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="@since 2.0"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="identifier" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="feature" lowerBound="1"
        eType="#//FeatureRef" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="valid" lowerBound="1" eType="#//ValidityPeriod"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="userAuthentication" lowerBound="1"
        eType="#//EvaluationInstructions" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="capacity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vivid" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pack" lowerBound="1" eType="#//PersonalLicensePack"
        eOpposite="#//PersonalLicensePack/grants"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PersonalLicensePack" eSuperTypes="#//PersonalLicensePackDescriptor">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="@since 2.0"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="license" lowerBound="1"
        eType="#//PersonalLicenseRequisites" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="grants" upperBound="-1"
        eType="#//PersonalFeatureGrant" containment="true" eOpposite="#//PersonalFeatureGrant/pack"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PersonalLicenseRequisites" eSuperTypes="#//LicenseRequisites #//PersonalLicenseRequisitesDescriptor">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="@since 2.0"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="user" lowerBound="1" eType="#//UserRef"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProductRef" eSuperTypes="#//ProductRefDescriptor">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="@since 2.0"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="identifier" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Signature" eSuperTypes="#//SignatureDescriptor">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="@since 2.0"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" upperBound="-1"
        eType="#//SignatureAttribute" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//Signature"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SignatureAttribute" eSuperTypes="#//SignatureAttributeDescriptor">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="@since 2.0"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UserGrant" eSuperTypes="#//UserGrantDescriptor">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="@since 2.0"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="user" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="authentication" lowerBound="1"
        eType="#//EvaluationInstructions" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UserRef" eSuperTypes="#//UserRefDescriptor">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="@since 2.0"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="identifier" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ValidityPeriod" abstract="true" interface="true"
      eSuperTypes="#//ValidityPeriodDescriptor">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="@since 2.0"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ValidityPeriodClosed" eSuperTypes="#//ValidityPeriod #//ValidityPeriodClosedDescriptor">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="@since 2.0"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="from" ordered="false" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="until" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VersionMatch" eSuperTypes="#//VersionMatchDescriptor">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="@since 2.0"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rule" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
