<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="shipments" nsURI="http://www.eclipse.org/passage/lic/shipments/0.1.0"
    nsPrefix="org.eclipse.passage.lic">
  <eClassifiers xsi:type="ecore:EClass" name="Personal">
    <eStructuralFeatures xsi:type="ecore:EReference" name="licenses" upperBound="-1"
        eType="#//PersonalLicense" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Floating">
    <eStructuralFeatures xsi:type="ecore:EReference" name="licenses" upperBound="-1"
        eType="#//FloatingLicense" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PersonalLicenseDescriptor" instanceClassName="org.eclipse.passage.lic.shipments.PersonalLicenseDescriptor"
      abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="PersonalLicense" eSuperTypes="#//PersonalLicenseDescriptor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="user" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="license" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FloatingLicenseDescriptor" instanceClassName="org.eclipse.passage.lic.shipments.FloatingLicenseDescriptor"
      abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="FloatingLicense" eSuperTypes="#//FloatingLicenseDescriptor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="company" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="license" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
