###############################################################################
# Copyright (c) 2020, 2021 ArSysOp and others
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# https://www.eclipse.org/legal/epl-2.0/.
#
# SPDX-License-Identifier: EPL-2.0
#
# Contributors:
#     Alexander Fedorov (ArSysOp) - initial API and implementation
###############################################################################
name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Set up Maven
      uses: stCarolas/setup-maven@v4.5
      with:
        maven-version: 3.9.0
    - name: Configure Maven
      run: echo "MAVEN_OPTS='-Xmx2048m'" > ~/.mavenrc
    - name: Cache maven repo
      uses: actions/cache@v2
      env:
        cache-name: cache-maven-repo
      with:
        # maven files are stored in `~/.m2/repository` on Linux/macOS
        path: |
          ~/.m2/repository
          !~/.m2/repository/org/eclipse/passage
          !~/.m2/repository/.cache/tycho
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.sha1') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Build with Maven
      run: mvn clean verify --no-transfer-progress -U -P baseline-check,coverage
    - name: Publish coverage
      run: bash <(curl -s https://codecov.io/bash)
