###############################################################################
# Copyright (c) 2022, 2025 Contributors to Eclipse Foundation
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# https://www.eclipse.org/legal/epl-2.0/.
#
# SPDX-License-Identifier: EPL-2.0
#
# Contributors:
#     see git history
###############################################################################
name: Request license-review

on:
  issue_comment:
    types: [created]

jobs:
  call-license-check:
    permissions:
      pull-requests: write
    uses: eclipse-dash/dash-licenses/.github/workflows/mavenLicenseCheck.yml@master
    with:
      projectId: technology.passage
    secrets:
      gitlabAPIToken: ${{ secrets.PASSAGE_GITLAB_API_TOKEN }}
